FROM korosuke613/ubuntu-texlive-ja-devcontainer:latest
# FROM korosuke613/ubuntu-texlive-ja:latest

ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID




# Install needed packages and setup non-root user. Use a separate RUN statement to add your own dependencies.
COPY library-scripts/*.sh library-scripts/*.env /tmp/library-scripts/
RUN yes | unminimize 2>&1 \ 
    && bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "true" "true" \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/* /tmp/library-scripts


RUN usermod -d /home/$USERNAME -m $USERNAME
RUN usermod -aG sudo user 

RUN echo "root:root" | chpasswd
RUN echo "$USERNAME:$USERNAME" | chpasswd
WORKDIR /home/${USERNAME}/project
RUN apt-get update -y && apt-get -y install git software-properties-common htop cmake openssh-server

RUN git config --global --add safe.directory /home/${USERNAME}/project
WORKDIR /home/${USERNAME}/project

# # # # install some utilities


# USER $USERNAME
# MAINTAINER Futa HIRAKOBA

# RUN apt-get update && apt-get install -y \
#     git \
#     cpanminus \
#     texlive-extra-utils \
#     make \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*

# RUN cpanm Log::Log4perl Log::Dispatch::File YAML::Tiny File::HomeDir Unicode::GCString