version: "3"
services:
  ubuntu-texlive-ja:
    build: .
    # image: kei0709/ubuntu_latex_ja:v1
    command: sleep infinity
    volumes:
      - ../:/home/project
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
        read_only: true
      - type: bind
        source: ~/.gitconfig
        target: /etc/gitconfig
        read_only: true
      - ./.latexmkrc:/root/.latexmkrc
    environment:
      SHELL: "/bin/bash"